repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: uv run ruff check --fix --exit-non-zero-on-fix
        language: system
        types: [python]
      - id: format
        name: format
        entry: uv run ruff format
        language: system
        types: [python]
